rsa_psa_sha256 should have salt length of 32
hajimehoshi/webpackage pull request #2
Opened 2018-02-06 03:10 UTC by nyaxt

Not sure what we can do about the test. Iterate through the interface{} and make []uint8 all string?

2018-02-06 04:43 UTC, hajimehoshi requested changes

2018-02-06 04:43 UTC, hajimehoshi commented on go/signedexchange/signedexchange_test.go
> +	t.Errorf("%#+v", decoded) // FIXME: dousiyou
dousiyou ne

2018-02-06 06:43 UTC, hajimehoshi commented on go/signedexchange/signedexchange_test.go
> +	t.Errorf("%#+v", decoded) // FIXME: dousiyou
https://github.com/WICG/webpackage/pull/119/commits/38c496415ca945dd369fcf3576f2a5416d63f9fb ko shita

2018-02-06 07:02 UTC, nyaxt commented on go/signedexchange/signedexchange_test.go
> +	t.Errorf("%#+v", decoded) // FIXME: dousiyou
lgtm myside

2018-02-08 06:52 UTC, hajimehoshi commented
Adopted by https://github.com/hajimehoshi/webpackage/commit/99b672c46ca1899e630688701fedf8a4b3c92f7f

2018-02-08 06:52 UTC, closed without merging