Signature header should have some label
hajimehoshi/webpackage pull request #5
Opened 2018-02-06 05:18 UTC by nyaxt

As suggested by @irori

2018-02-06 05:59 UTC, hajimehoshi requested changes

2018-02-06 05:59 UTC, hajimehoshi commented on go/signedexchange/signer.go
> +		"%s; sig=*%s; validityUrl=\"%s\"; integrity=\"%s\"; certUrl=\"%s\"; certSha256=*%s; date=%d; expires=%d",
You can use `%q` instead of `\"%s\"`

2018-02-06 07:01 UTC, nyaxt commented on go/signedexchange/signer.go
> +		"%s; sig=*%s; validityUrl=\"%s\"; integrity=\"%s\"; certUrl=\"%s\"; certSha256=*%s; date=%d; expires=%d",
done

2018-02-06 07:29 UTC, hajimehoshi commented
Does this pass the existing tests? If not, please update that...

2018-02-08 08:09 UTC, hajimehoshi approved these changes

2018-02-08 08:10 UTC, hajimehoshi commented
I'll fix the test. Thank you!

2018-02-08 08:10 UTC, merged